package com.redhat.bpms.examples.mortgage;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@org.kie.api.definition.type.Label(value = "Validation Error")
public class ValidationError  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Cause of Error")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String cause;

    public ValidationError() {
    }

    public ValidationError(java.lang.String cause) {
        this.cause = cause;
    }


    
    public java.lang.String getCause() {
        return this.cause;
    }
    @XmlElement
    public void setCause(  java.lang.String cause ) {
        this.cause = cause;
    }




}